version: 0.0
os: linux

files:
  - source: Frontend/moveinn/
    destination: /var/www/Frontend
    file_exists_behavior: OVERWRITE

  # - source: Backend/Backend/bin/Release/net8.0/publish/
  #   destination: /var/www/backend

hooks:
  BeforeInstall:
    # - location: scripts/before_install_backend.sh
    #   timeout: 300
    - location: scripts/before_install_frontend.sh
      timeout: 300
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
  ApplicationStart:
    # - location: scripts/start_backend.sh
    #   timeout: 300
    - location: scripts/start_frontend.sh
      timeout: 300
