version: 0.0
os: linux

files:
  - source: Frontend/moveinn
    destination: /var/www/Frontend
file_exists_behavior: OVERWRITE       

hooks:
  BeforeInstall:
    - location: scripts/before_install_frontend.sh
      timeout: 180
      runas: root        

  AfterInstall:
    - location: scripts/after_install_frontend.sh
      timeout: 600
      runas: ubuntu        

  ApplicationStart:
    - location: scripts/start_frontend.sh
      timeout: 120
      runas: ubuntu        

