version: 0.0
os: linux

<<<<<<< Updated upstream
files:
  - source: Frontend/moveinn/
    destination: /var/www/frontend

  - source: Backend/Backend/bin/Release/net8.0/publish/
    destination: /var/www/backend

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_backend.sh
      timeout: 300
    - location: scripts/start_frontend.sh
      timeout: 300
=======
# Copia de artefactos desde tu bundle de CodeDeploy
files:
  - source: Backend/bin/Release/net8.0/publish/
    destination: /var/www/moveinn/backend/


  - source: Frontend/out/
    destination: /var/www/moveinn/frontend/

hooks:
  BeforeInstall:
    - location: scripts/stop-backend.sh
      timeout: 300
      runas: root
    - location: scripts/stop-frontend.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/install-backend-deps.sh
      timeout: 300
      runas: root
    - location: scripts/install-frontend-deps.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start-backend.sh
      timeout: 300
      runas: root
    - location: scripts/start-frontend.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/healthcheck.sh
      timeout: 60
      runas: root
>>>>>>> Stashed changes
