version: 0.0
os: linux

files:
  - source: Frontend/moveinn
    destination: /var/www/Frontend
    overwrite: yes

hooks:
  BeforeInstall:
    - location: scripts/before_install_frontend.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_frontend.sh
      timeout: 120
