version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/frontend

hooks:
  BeforeInstall:
    - location: scripts/clean_old.sh
      timeout: 300
  AfterInstall:
    - location: scripts/install_deps.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_frontend.sh
      timeout: 300
