name: Deploy MoveInn Backend

on:
  push:
    paths:
      - 'Backend/**'          
    branches:
      - main
     

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: read          

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}   
          aws-region:            us-east-1                          

      - name: Trigger CodeDeploy deployment
        run: |
          aws deploy create-deployment \
            --application-name      MoveInnBackend \
            --deployment-group-name MoveInnProd \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }} \
            --description "Auto-deploy desde GitHub Actions @${{ github.sha }}" \
            --region us-east-1        # ← misma región que arriba
