name: Deploy MoveInn Frontend

on:
  push:
    paths:
      - 'Frontend/**'          
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            us-east-1

      - name: Trigger Frontend CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name      MoveInnFrontend \
            --deployment-group-name MoveInnFrontend \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }} \
            --description "Auto-deploy Frontend @${{ github.sha }}" \
            --region us-east-1
