name: Deploy MoveInn

on:
  push:
    branches: [main]
    paths:
      - 'Backend/**'
      - 'Frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Configurar AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            us-east-1

      - name: Deploy Backend
        run: |
          aws deploy create-deployment \
            --application-name MoveInnBackend \
            --deployment-group-name MoveInnProd \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }} \
            --description "Backend auto-deploy @${{ github.sha }}" \
            --region us-east-1

      - name: Deploy Frontend
        run: |
          aws deploy create-deployment \
            --application-name MoveInnFrontend \
            --deployment-group-name MoveInnFrontend \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }} \
            --description "Frontend auto-deploy @${{ github.sha }}" \
            --region us-east-1
